FROM ruby:2.5.3
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    postgresql-client \
    yarn

WORKDIR /product-register
COPY Gemfile Gemfile.lock /product-register/
RUN bundle install
# host側のものをコンテナ側に渡す マウントしない
COPY . . 
CMD ["rails", "s"]